name: netpbm
description: Dart netpbm format image creator
version: 1.0.0
# homepage: https://github.com/taleroangel/dart_netpbm

environment:
    sdk: ">=2.16.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
    lints: ^1.0.0
    test: ^1.16.0
