import 'image.dart';
import 'dart:io';
import 'static_matrix.dart';

class ImageMono extends Image<bool> {
  /// Create a new monochromatic image (values go from 0 to 1)
  ImageMono({required int width, required int height})
      : super(height: height, width: width, maxValue: 1, defaultValue: false);

  /// Create a mono image from a matrix
  ImageMono.fromMatrix(StaticMatrix<bool> matrix)
      : super.allParameters(maxValue: 1, pixels: matrix);

  @override
  void toFile(String baseName) {
    // Open file
    var file = File(baseName + '.pbm').openWrite();

    // Write file type
    file.write('P1\n');
    // Write commentary
    file.write('# File generated by NETPBM Dart library by @taleroangel\n');
    file.write('# visit: https://github.com/taleroangel/dart_netpbm\n');
    // Write size
    file.write('$width $height\n');

    for (int i = 0; i < height; i++) {
      for (int j = 0; j < width; j++) {
        file.write('${pixels[i][j] ? '1' : '0'} ');
      }
      file.write('\n');
    }

    // Close file
    file.close();
  }
}
